<?php

/**
 * @file
 * Module file for EF Commerce
 */

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function ef_commerce_commerce_checkout_pane_info_alter(&$checkout_panes) {
  $checkout_panes['checkout_donate']['page'] = 'registration';
  $checkout_panes['checkout_donate']['title'] = t('Donate');
  $checkout_panes['checkout_donate']['weight'] = -19;
  $checkout_panes['checkout_donate']['enabled'] = TRUE;
  $checkout_panes['checkout_review']['enabled'] = FALSE;
}